package tree

const TREE_TYPE_BST = 0
const TREE_TYPE_BINARY = 1
const TREE_TYPE_AVL = 2

const PRETTY_PRINT_TREE = true

// All related to Tries
const TRIE_DEFAULT_VALUE = -1
const TRIE_FINAL_NODE_KEY = "endVal"
const TRIE_DEFAULT_SUBSTRING_MATCH = true
const TRIE_DEFAULT_CASE_INSENSITIVE = true
const TRIE_DEFAULT_STRIP_STOP_WORDS = true
const TRIE_DEFAULT_STRIP_PUNCTUATIONS = false
const TRIE_DEFAULT_WORD_SEPARATOR = true
